레이아웃 및 GNB 구현
TRIPONG-2022/frontend pull request #28
Opened 2022-07-02 14:37 UTC by seongjin2427

# Pull Request

- [x] Feature

## Summary

- 메인 레이아웃 구현
- 메인 레이아웃의 GNB(Header) 및 네비게이션  구현

## Describe your changes

- Layout
  - fullwidth Props 유무로 max-width 1280px 적용을 지정할 수 있음
  - `<MainLayout>` max-width 1280px 미 적용
  - `<MainLayout fullWidth>` max-width 1280px 적용

- GNB (Header)
  - 태블릿 크기 `(SCREEN_TABLET)`에서부터 HamburgerButton 활성화 및 네비게이션 창 적용
  - Logo 및 검색 아이콘 SVG 파일 및 컴포넌트 추가

- 미디어 쿼리 디바이스별 상수 정의
  - `SCREEN_MOBILE = '@media (max-width: 768px)';`
  - `SCREEN_TABLET = '@media (max-width: 1024px)';`
  - `SCREEN_DESKTOP = '@media (min-width: 1025px)';`
- HamburgerButton styled-component화 완료
- 로그인 유무에 따른 로그인/회원가입 ↔ 로그아웃/마이페이지 버튼 전환

## Issue number and link

- 이슈 #25 

## ETC

리덕스 적용 후 GNB의 isLogin Props 연결 필요

2022-07-04 03:29 UTC, sangrimlee commented
branch가 main branch로 되어있는데 수정해주셔야 될 것 같아요.

2022-07-04 05:02 UTC, seongjin2427 commented
으얽 변경했습니다 ㅠㅠ

2022-07-04 09:55 UTC, jma1020 approved these changes
확인했습니다!! 완전 Good 코드입니다 😊

2022-07-05 09:40 UTC, sangrimlee requested changes

2022-07-05 09:40 UTC, sangrimlee commented on styles/screen.ts
> +export const SCREEN_MOBILE = '@media (min-width: 768px)';
`SCREEN_MOBILE`을 `SCREEN_TABLET`으로 `SCREEN_TABLET`을 `SCREEN_DESKTOP`으로 변경해야 될 것 같아요.

2022-07-05 09:40 UTC, sangrimlee commented on layouts/NavigationDiv/NavigationDiv.tsx
> +function NavigationDiv({ toggle, isLogin }: NavigationDivProps) {
`NavigationDiv`보다는 `MobileNavigation`이라던지 조금 더 명확한 이름이 좋지 않을까요??

2022-07-05 09:40 UTC, sangrimlee commented on layouts/MainLayout/MainLayout.styled.ts
> +export const Footer = styled.div`
`div`보다는 `footer`를 쓰는게 Semantic 하지 않을까요?
이 부분 말고도  Body 부분도 `main`을 GNB에서의 ContainerNav는 `nav`태그를 `header`태그로 한 번 감싸서 쓰는게 더 semantic 할 것 같아요!

2022-07-05 09:40 UTC, sangrimlee commented on components/shared/HamburgerButton/HamburgerButton.tsx
> +interface XButtonProps {
HamburgerButtonProps로 바꿔줘야 될 것 같아요:)

2022-07-05 11:05 UTC, seongjin2427 commented on components/shared/HamburgerButton/HamburgerButton.tsx
> +interface XButtonProps {
핫 수정 완료 했슴당

2022-07-05 13:16 UTC, seongjin2427 commented on styles/screen.ts
> +export const SCREEN_MOBILE = '@media (min-width: 768px)';
반영 완료했습니닷! 😁

2022-07-05 13:16 UTC, seongjin2427 commented on layouts/NavigationDiv/NavigationDiv.tsx
> +function NavigationDiv({ toggle, isLogin }: NavigationDivProps) {
저도 좀 더 명확한 이름으로 하고 싶었는데, MobileNavigation으로 변경했습니다! 감사합니다!

2022-07-05 13:16 UTC, seongjin2427 commented on layouts/MainLayout/MainLayout.styled.ts
> +export const Footer = styled.div`
Sementic하게 작성해야 한다는것을 알고는 있었는데, 프로젝트에서는 크게 신경을 안 쓰고 있었네요!
피드백 감사합니다!
바로 반영했어요!

2022-07-06 13:05 UTC, sangrimlee approved these changes
고생하셨어요👍

2022-07-07 09:13 UTC, merged