공용화 Modal 구현
TRIPONG-2022/frontend pull request #29
Opened 2022-07-05 09:05 UTC by jma1020

# Pull Request
 - [x] Feature

## Summary
- 공용화 Modal 컴포넌트 구현
- Modal 테스트 페이지 작성

## Describe your changes
- Modal을 사용할 페이지에서 useModal hook 사용
- compound components 패턴으로 Modal 컴포넌트 사용

## Issue number and link
#23 
## ETC
- 반응형을 고려해서 보완 고려 중

2022-07-06 13:11 UTC, sangrimlee requested changes

2022-07-06 13:11 UTC, sangrimlee commented on components/shared/Modal/Modal.tsx
> +const ModalComponent = ({ isModal, close, children }: ModalProps) => {
ModalCompoment보다는 Modal이 더 좋을 것 같아요!

2022-07-06 13:11 UTC, sangrimlee commented on hooks/useModal.ts
> +  return { isModal, open, close };
저번에 말씀드렸던 Tuple을 쓰는 건 어떨까요?
예를 들어 하나의 페이지에 여러개의 모달을 관리하고 싶을 때 다음과 같이 조금 코드가 길어질 것 같아요!
```typescript
const { isModal:isModal1 }=useModal();

const { isModal:isModal2 }=useModal();
```

2022-07-08 05:23 UTC, jma1020 commented on components/shared/Modal/Modal.tsx
> +const ModalComponent = ({ isModal, close, children }: ModalProps) => {
감사합니다!! 네이밍 변경 반영했습니다~

2022-07-08 05:23 UTC, jma1020 commented on hooks/useModal.ts
> +  return { isModal, open, close };
오오 그렇겠네요.. 한 개 이상 생각을 안하고 있었네요 감사합니다!!  😊🥰

2022-07-09 11:08 UTC, sangrimlee approved these changes

2022-07-13 11:59 UTC, seongjin2427 approved these changes
확인했습니다! 😀
고생하셨어요!!

2022-07-15 07:51 UTC, merged